"""initial_schema

Revision ID: c4151733b728
Revises: b2344c4cb16e
Create Date: 2025-11-20 06:22:32.240146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4151733b728'
down_revision = 'b2344c4cb16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
